steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/doitintl-demo/demo-automl-loan', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/doitintl-demo/demo-automl-loan']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'demo-automl-loan', '--image', 'gcr.io/doitintl-demo/demo-automl-loan', '--region', 'europe-west4', '--platform', 'managed', '--memory', '256M', '--allow-unauthenticated', '--max-instances', '5']
images:
- gcr.io/doitintl-demo/demo-automl-loan